In [13]:
from libraries.import_export_data_objects import import_export_data as Import_Export_Data
from libraries.altair_renderings import AltairRenderings
from libraries.utility import Utility
import pandasql as psql
import numpy as np
import pandas as pd
import os
import altair as alt
my_altair = AltairRenderings()
my_data = Import_Export_Data()

In [15]:
dt = my_altair.my_data_object
world_source = dt.get_world_countries_by_iso_label()

In [16]:
eu_countries=['Austria','Belgium','Croatia','Czech Republic','Denmark','Finland','France','Germany','Greece','Hungary',
        'Italy','Netherlands','Poland','Portugal','Spain','Sweden','United Kingdom']

In [40]:
file_name = "WtoData_services_imports.csv"
data_directory = "data"
trade_balance_sub_dir = "trade_balance_datasets"
file_path = os.path.join(my_data.get_this_dir(),data_directory,trade_balance_sub_dir,file_name)

In [57]:
world_service_imp = pd.read_csv(file_path, skiprows = 2, header = 0)
world_service_imp.head()

,Reporting Economy,Product/Sector,Partner Economy,2015,2016,2017,2018,2019,2020,Unnamed: 9
0,World,BOP6 - SC - Transport,World,1068277.0,1019892.0,1118250.0,1247826.0,1240422.0,996080.0,NaN
1,World,BOP6 - SC1 - Sea transport,World,489363.0,449366.0,502883.0,557160.0,548421.0,500345.0,NaN
2,World,BOP6 - SC11 - Passenger (Sea),World,20845.0,20496.0,17982.0,NaN,NaN,NaN,NaN
3,World,BOP6 - S - Memo item: Total services,World,4895497.0,4921183.0,5324019.0,5789905.0,5947811.0,4681535.0,NaN
4,World,BOP6 - GSOX - Memo item: Goods and commercial ...,World,20658321.0,20220409.0,22272783.0,24513487.0,24136094.0,21278981.0,NaN

In [63]:
eu_service_import = world_service_imp.loc[(world_service_imp['Reporting Economy'].isin(eu_countries)) & (world_service_imp['Partner Economy'].isin(eu_countries))]

In [69]:
eu_service_import_2020 = eu_service_import[['Reporting Economy','Partner Economy','2020']]

In [82]:
df = pd.DataFrame(None, columns = eu_countries, index =eu_countries)
eu_service_import_2020.columns

Index(['Reporting Economy', 'Partner Economy', '2020'], dtype='object')

In [83]:
for i in range(len(df)):
    for j in range(len(df)):
        source = df.index[i]
        partner = df.columns[j]
        df.iloc[i,j] = eu_service_import_2020[(eu_service_import_2020['Reporting Economy'] == source) & (eu_service_import_2020['Partner Economy'] == partner)]['2020'].sum()

In [93]:
df.column

,Austria,Belgium,Croatia,Czech Republic,Denmark,Finland,France,Germany,Greece,Hungary,Italy,Netherlands,Poland,Portugal,Spain,Sweden,United Kingdom
Austria,0.0,1072.0,1037.0,2237.0,408.0,623.0,1259.0,16176.0,318.0,2621.0,2159.0,2027.0,3392.0,187.0,777.0,1556.0,3678.0
Belgium,1265.0,0.0,186.0,1516.0,1184.0,644.0,17511.0,16145.0,633.0,753.0,5534.0,22195.0,2580.0,1198.0,3764.0,1482.0,13444.0
Croatia,216.0,72.0,0.0,51.0,38.0,6.0,80.0,395.0,9.0,53.0,82.0,84.0,33.0,3.0,31.0,63.0,186.0
Czech Republic,1145.0,389.0,157.0,0.0,260.0,111.0,1056.0,5906.0,86.0,341.0,789.0,948.0,887.0,81.0,471.0,314.0,1580.0
Denmark,0.0,0.0,111.0,434.0,0.0,0.0,0.0,0.0,0.0,613.0,0.0,0.0,1686.0,0.0,0.0,5583.0,9759.0
Finland,385.0,774.0,40.0,327.0,1838.0,0.0,1334.0,4583.0,138.0,251.0,935.0,2833.0,1426.0,242.0,771.0,5363.0,2411.0
France,1699.0,17371.0,304.0,1837.0,1674.0,930.0,0.0,39703.0,1759.0,1545.0,14449.0,16885.0,7464.0,4163.0,17735.0,3675.0,28456.0
Germany,20726.0,0.0,0.0,7733.0,0.0,0.0,21624.0,0.0,0.0,4609.0,13528.0,24262.0,15451.0,0.0,9149.0,0.0,31976.0
Greece,0.0,0.0,19.0,107.0,190.0,0.0,0.0,0.0,0.0,98.0,0.0,0.0,175.0,0.0,0.0,159.0,1578.0
Hungary,1923.0,555.0,274.0,623.0,301.0,45.0,680.0,5005.0,78.0,0.0,487.0,1003.0,773.0,38.0,212.0,178.0,1312.0
Italy,2717.0,2283.0,650.0,1604.0,1480.0,241.0,10013.0,11351.0,3005.0,1103.0,0.0,4864.0,3053.0,747.0,3362.0,1195.0,8223.0
Netherlands,2052.0,17924.0,133.0,2488.0,2392.0,1106.0,16148.0,32206.0,628.0,1430.0,7211.0,0.0,6082.0,938.0,7316.0,3547.0,34931.0
Poland,1494.0,1246.0,383.0,2022.0,1477.0,420.0,2494.0,10381.0,392.0,511.0,1514.0,3368.0,0.0,181.0,829.0,1249.0,4171.0
Portugal,66.0,541.0,11.0,54.0,62.0,52.0,1613.0,1566.0,36.0,100.0,477.0,830.0,98.0,0.0,3160.0,116.0,2171.0
Spain,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7406.0
Sweden,611.0,1732.0,140.0,339.0,5149.0,7118.0,2779.0,8498.0,273.0,371.0,1273.0,4886.0,2197.0,183.0,1502.0,0.0,9548.0
United Kingdom,1746.0,3509.0,378.0,1183.0,2395.0,425.0,15887.0,13818.0,2269.0,1045.0,4956.0,9491.0,5319.0,1628.0,10656.0,5627.0,0.0

In [161]:
df1 = df.stack().reset_index()
df1.columns = ['Source Country','Trading Partner','Total Volume']
df1.shape

(289, 3)

In [163]:
df1['ordered-cols'] = df1.apply(lambda x: '-'.join(sorted([x['Source Country'],x['Trading Partner']])), axis=1)
df1 = df1.drop_duplicates(['ordered-cols'])
df1

,Source Country,Trading Partner,Total Volume,ordered-cols
0,Austria,Austria,0.0,Austria-Austria
1,Austria,Belgium,1072.0,Austria-Belgium
2,Austria,Croatia,1037.0,Austria-Croatia
3,Austria,Czech Republic,2237.0,Austria-Czech Republic
4,Austria,Denmark,408.0,Austria-Denmark
...,...,...,...,...
253,Spain,Sweden,0.0,Spain-Sweden
254,Spain,United Kingdom,7406.0,Spain-United Kingdom
270,Sweden,Sweden,0.0,Sweden-Sweden
271,Sweden,United Kingdom,9548.0,Sweden-United Kingdom
288,United Kingdom,United Kingdom,0.0,United Kingdom-United Kingdom

In [165]:
alt.Chart(df1).mark_rect().encode(
    x="Source Country:N",
    y="Trading Partner:N",
    color='Total Volume:Q'
).resolve_scale(color="independent",).properties(
    title='EU Domestic Trading Volume'
)

alt.Chart(...)

In [ ]:
file_name_service_imports = "WtoData_services_imports.csv"
file_name_service_exports = "WtoData_services_imports.csv"
file_name_merch_imports = "WtoData_merchandise_imports.csv"
file_name_merch_exports = "WtoData_merchandise_exports.csv"

file_names = ['WtoData_services_imports.csv','WtoData_services_imports.csv','WtoData_merchandise_imports.csv','WtoData_merchandise_exports.csv']

data_directory = "data"
trade_balance_sub_dir = "trade_balance_datasets"
file_path = os.path.join(my_data.get_this_dir(),data_directory,trade_balance_sub_dir,file_name)

In [1]:
from libraries.import_export_data_objects import import_export_data as Import_Export_Data
from libraries.altair_renderings import AltairRenderings
from libraries.utility import Utility
import pandasql as psql
import numpy as np
import pandas as pd
import os
import altair as alt
my_altair = AltairRenderings()
my_data = Import_Export_Data()

In [4]:
test = my_data.get_WTO_individual_file_name()
test

['/Users/Stan/Desktop/UCB_MIDS/W209/w209_spring_2022_thu_4_pm_team_4_web/data/trade_balance_datasets/WtoData_services_imports.csv',
 '/Users/Stan/Desktop/UCB_MIDS/W209/w209_spring_2022_thu_4_pm_team_4_web/data/trade_balance_datasets/WtoData_services_imports.csv',
 '/Users/Stan/Desktop/UCB_MIDS/W209/w209_spring_2022_thu_4_pm_team_4_web/data/trade_balance_datasets/WtoData_merchandise_imports.csv',
 '/Users/Stan/Desktop/UCB_MIDS/W209/w209_spring_2022_thu_4_pm_team_4_web/data/trade_balance_datasets/WtoData_merchandise_exports.csv']

In [11]:
eu_countries=['Austria','Belgium','Croatia','Czech Republic','Denmark','Finland','France','Germany','Greece','Hungary',
        'Italy','Netherlands','Poland','Portugal','Spain','Sweden','United Kingdom']
wto_ser_imports.columns

Index(['Reporting Economy', 'Product/Sector', 'Partner Economy', '2015',
       '2016', '2017', '2018', '2019', '2020', 'Unnamed: 9'],
      dtype='object')

In [109]:
wto_ser_imports = pd.read_csv(test[0], skiprows = 2, header = 0)
wto_ser_exports = pd.read_csv(test[1], skiprows = 2, header = 0)

In [110]:
wto_ser_imports = wto_ser_imports.loc[(wto_ser_imports['Reporting Economy'].isin(eu_countries)) & (wto_ser_imports['Partner Economy'].isin(eu_countries))]
wto_ser_imports = wto_ser_imports.drop(columns=['Product/Sector','Unnamed: 9'])
wto_ser_imports = wto_ser_imports.groupby(['Reporting Economy', 'Partner Economy']).agg(ser_imports_2015=('2015','sum'),
                                                                              ser_imports_2016=('2016','sum'),
                                                                              ser_imports_2017=('2017','sum'),
                                                                              ser_imports_2018=('2018','sum'),
                                                                              ser_imports_2019=('2019','sum'),
                                                                              ser_imports_2020=('2020','sum'))

wto_ser_exports = wto_ser_exports.loc[(wto_ser_exports['Reporting Economy'].isin(eu_countries)) & (wto_ser_exports['Partner Economy'].isin(eu_countries))]
wto_ser_exports = wto_ser_exports.drop(columns=['Product/Sector','Unnamed: 9'])
wto_ser_exports = wto_ser_exports.groupby(['Reporting Economy', 'Partner Economy']).agg(ser_exports_2015=('2015','sum'),
                                                                              ser_exports_2016=('2016','sum'),
                                                                              ser_exports_2017=('2017','sum'),
                                                                              ser_exports_2018=('2018','sum'),
                                                                              ser_exports_2019=('2019','sum'),
                                                                              ser_exports_2020=('2020','sum'))

In [114]:
df_concat = wto_ser_imports.merge(wto_ser_exports, how = 'outer', left_index = True, right_index = True)
df_concat = df_concat.reset_index()

In [115]:
df_concat.head()

,Reporting Economy,Partner Economy,ser_imports_2015,ser_imports_2016,ser_imports_2017,ser_imports_2018,ser_imports_2019,ser_imports_2020,ser_exports_2015,ser_exports_2016,ser_exports_2017,ser_exports_2018,ser_exports_2019,ser_exports_2020
0,Austria,Belgium,1272.0,1465.0,1624.0,1730.0,1783.0,1072.0,1272.0,1465.0,1624.0,1730.0,1783.0,1072.0
1,Austria,Croatia,1361.0,1565.0,1706.0,1848.0,1867.0,1037.0,1361.0,1565.0,1706.0,1848.0,1867.0,1037.0
2,Austria,Czech Republic,2003.0,2215.0,2416.0,2569.0,2531.0,2237.0,2003.0,2215.0,2416.0,2569.0,2531.0,2237.0
3,Austria,Denmark,295.0,325.0,348.0,409.0,422.0,408.0,295.0,325.0,348.0,409.0,422.0,408.0
4,Austria,Finland,820.0,792.0,889.0,1121.0,1466.0,623.0,820.0,792.0,889.0,1121.0,1466.0,623.0

In [ ]:
world_service_imp = pd.read_csv(file_path, skiprows = 2, header = 0)
eu_service_import = world_service_imp.loc[(world_service_imp['Reporting Economy'].isin(eu_countries)) & (world_service_imp['Partner Economy'].isin(eu_countries))]
df = pd.DataFrame(None, columns = eu_countries, index =eu_countries)

In [120]:
def load_and_clean_up_individual_WTO_files():
    test = my_data.get_WTO_individual_file_name()

    eu_countries=['Austria','Belgium','Croatia','Czech Republic','Denmark','Finland','France','Germany','Greece','Hungary',
        'Italy','Netherlands','Poland','Portugal','Spain','Sweden','United Kingdom']
        
    wto_ser_imports = pd.read_csv(test[0], skiprows = 2, header = 0)
    wto_ser_exports = pd.read_csv(test[1], skiprows = 2, header = 0)
    
    wto_ser_imports = wto_ser_imports.loc[(wto_ser_imports['Reporting Economy'].isin(eu_countries)) & (wto_ser_imports['Partner Economy'].isin(eu_countries))]
    wto_ser_imports = wto_ser_imports.drop(columns=['Product/Sector','Unnamed: 9'])
    wto_ser_imports = wto_ser_imports.groupby(['Reporting Economy', 'Partner Economy']).agg(ser_imports_2015=('2015','sum'),
                                                                              ser_imports_2016=('2016','sum'),
                                                                              ser_imports_2017=('2017','sum'),
                                                                              ser_imports_2018=('2018','sum'),
                                                                              ser_imports_2019=('2019','sum'),
                                                                              ser_imports_2020=('2020','sum'))

    wto_ser_exports = wto_ser_exports.loc[(wto_ser_exports['Reporting Economy'].isin(eu_countries)) & (wto_ser_exports['Partner Economy'].isin(eu_countries))]
    wto_ser_exports = wto_ser_exports.drop(columns=['Product/Sector','Unnamed: 9'])
    wto_ser_exports = wto_ser_exports.groupby(['Reporting Economy', 'Partner Economy']).agg(ser_exports_2015=('2015','sum'),
                                                                              ser_exports_2016=('2016','sum'),
                                                                              ser_exports_2017=('2017','sum'),
                                                                              ser_exports_2018=('2018','sum'),
                                                                              ser_exports_2019=('2019','sum'),
                                                                              ser_exports_2020=('2020','sum'))
    
    df_concat = wto_ser_imports.merge(wto_ser_exports, how = 'outer', left_index = True, right_index = True)
    df_concat = df_concat.reset_index()
    return df_concat

In [121]:
test = load_and_clean_up_individual_WTO_files()

In [122]:
test

,Reporting Economy,Partner Economy,ser_imports_2015,ser_imports_2016,ser_imports_2017,ser_imports_2018,ser_imports_2019,ser_imports_2020,ser_exports_2015,ser_exports_2016,ser_exports_2017,ser_exports_2018,ser_exports_2019,ser_exports_2020
0,Austria,Belgium,1272.0,1465.0,1624.0,1730.0,1783.0,1072.0,1272.0,1465.0,1624.0,1730.0,1783.0,1072.0
1,Austria,Croatia,1361.0,1565.0,1706.0,1848.0,1867.0,1037.0,1361.0,1565.0,1706.0,1848.0,1867.0,1037.0
2,Austria,Czech Republic,2003.0,2215.0,2416.0,2569.0,2531.0,2237.0,2003.0,2215.0,2416.0,2569.0,2531.0,2237.0
3,Austria,Denmark,295.0,325.0,348.0,409.0,422.0,408.0,295.0,325.0,348.0,409.0,422.0,408.0
4,Austria,Finland,820.0,792.0,889.0,1121.0,1466.0,623.0,820.0,792.0,889.0,1121.0,1466.0,623.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,United Kingdom,Netherlands,9660.0,11480.0,12229.0,13718.0,13531.0,9491.0,9660.0,11480.0,12229.0,13718.0,13531.0,9491.0
268,United Kingdom,Poland,3729.0,5087.0,5558.0,5871.0,6356.0,5319.0,3729.0,5087.0,5558.0,5871.0,6356.0,5319.0
269,United Kingdom,Portugal,4229.0,3359.0,3259.0,3646.0,4138.0,1628.0,4229.0,3359.0,3259.0,3646.0,4138.0,1628.0
270,United Kingdom,Spain,21933.0,16794.0,17794.0,19356.0,19371.0,10656.0,21933.0,16794.0,17794.0,19356.0,19371.0,10656.0
271,United Kingdom,Sweden,4259.0,3547.0,4007.0,5994.0,6437.0,5627.0,4259.0,3547.0,4007.0,5994.0,6437.0,5627.0